### ISSUE TITLE
BookSeat logic needed.

### ISSUE THREAD

**Issue by shawnkoon** [shawnkoon/Airport-Simulator#4]
It needs to work with this code.

        res.bookSeat("DELTA", "123", SeatClass.first, 1, 'A');
		res.bookSeat("DELTA", "123", SeatClass.economy, 1, 'A');
		res.bookSeat("DELTA", "123", SeatClass.economy, 1, 'B');
		res.bookSeat("DELTA888", "123", SeatClass.business, 1, 'A'); //Invalid airline
		res.bookSeat("DELTA", "123haha7", SeatClass.business, 1, 'A'); //Invalid flightId
		res.bookSeat("DELTA", "123", SeatClass.economy, 1, 'A'); //already booked

If invalid, show proper error msg.

**Comment by cwade12c** [comment]
Done.
