### ISSUE TITLE
DisplaySystemDetails logic needed.

### ISSUE THREAD

**Issue by shawnkoon** [shawnkoon/Airport-Simulator#5]
It needs to work with this code.

     res.displaySystemDetails();

Not sure what kind of output we are suppose to display.  :P 
## <strong>Maybe we can think about this after everything.</strong>

But any suggestions are welcome. So, please leave comments if you have any idea.

**Comment by cwade12c** [comment]
Logic added. *NEED TO TEST*

**Comment by cwade12c** [comment]
Done.
