### ISSUE TITLE
FindAvailableFlights logic Needed.

### ISSUE THREAD

**Issue by shawnkoon** [shawnkoon/Airport-Simulator#6]
It needs to work with the following code snippet.

    res.findAvailableFlights("DEN", "LON");

# <Strong>Not sure about the display format.</Strong>

we can approach this after everything else like #5 .

**Comment by cwade12c** [comment]
Working on it.

**Comment by cwade12c** [comment]
Logic added. NEED TO TEST.

**Comment by shawnkoon** [comment]
kk

**Comment by shawnkoon** [comment]
Done
