### ISSUE TITLE
For createFlight cases. Can depart == destination?

### ISSUE THREAD

**Issue by shawnkoon** [shawnkoon/Airport-Simulator#7]
I assumed it was possible. 
ex) moving airplane to different port in that airport. 
ex) move plane to get serviced or whatever.

But if it is not i will fix it so please let me know

**Comment by cwade12c** [comment]
That would make sense. Should we add an additional parameter that determines the status of the flight? For example, refactor the method signature to

public void createFlight(String company, String depart, String destination, int year, int month, int day, String ticketID, String status)

A status can be passed in, such as:

Flight
Move
Maintenance

So in the case that the departure and destination WERE the same, we could easily display the status of that flight for more information (e.g. maintenance).

Thoughts?

**Comment by cwade12c** [comment]
Actually, adding that additional parameter would break the example code that we have to implement. So nevermind, even though it would have been cool.

**Comment by shawnkoon** [comment]
greattt
